-- MySQL Script generated by MySQL Workbench
-- 08/23/17 13:10:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema leidy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema leidy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `leidy` DEFAULT CHARACTER SET utf8 ;
USE `leidy` ;

-- -----------------------------------------------------
-- Table `leidy`.`Lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leidy`.`Lote` (
  `idLote` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT(10) NOT NULL,
  `FechaCompra` DATE NOT NULL,
  `Estado` ENUM('Engorde', 'Vendido') NOT NULL,
  `Valor` INT NOT NULL,
  PRIMARY KEY (`idLote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leidy`.`Novillos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leidy`.`Novillos` (
  `idNovillos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `EdadPromedio` VARCHAR(45) NOT NULL,
  `FechaIngreso` DATE NOT NULL,
  `Lote` VARCHAR(45) NOT NULL,
  `Lote_idLote` INT NOT NULL,
  PRIMARY KEY (`idNovillos`),
  INDEX `fk_Novillos_Lote_idx` (`Lote_idLote` ASC),
  CONSTRAINT `fk_Novillos_Lote`
    FOREIGN KEY (`Lote_idLote`)
    REFERENCES `leidy`.`Lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leidy`.`Isumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leidy`.`Isumos` (
  `idIsumos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Cantidad` VARCHAR(45) NOT NULL,
  `Valor` INT NOT NULL,
  `LotesDesig` INT NOT NULL,
  PRIMARY KEY (`idIsumos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leidy`.`Ganadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leidy`.`Ganadero` (
  `idGanadero` INT NOT NULL AUTO_INCREMENT,
  `Documento` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGanadero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leidy`.`Lote_has_Isumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leidy`.`Lote_has_Isumos` (
  `Lote_idLote` INT NOT NULL,
  `Isumos_idIsumos` INT NOT NULL,
  PRIMARY KEY (`Lote_idLote`, `Isumos_idIsumos`),
  INDEX `fk_Lote_has_Isumos_Isumos1_idx` (`Isumos_idIsumos` ASC),
  INDEX `fk_Lote_has_Isumos_Lote1_idx` (`Lote_idLote` ASC),
  CONSTRAINT `fk_Lote_has_Isumos_Lote1`
    FOREIGN KEY (`Lote_idLote`)
    REFERENCES `leidy`.`Lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lote_has_Isumos_Isumos1`
    FOREIGN KEY (`Isumos_idIsumos`)
    REFERENCES `leidy`.`Isumos` (`idIsumos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
