-- MySQL Script generated by MySQL Workbench
-- 08/15/17 12:54:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cuerpo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuerpo` (
  `Cod_Cuerpo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Soldados_cod_Soldados` INT NOT NULL,
  PRIMARY KEY (`Cod_Cuerpo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuartel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuartel` (
  `Cod_Cuartel` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`Cod_Cuartel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Soldados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Soldados` (
  `cod_Soldados` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Graduacion` VARCHAR(45) NULL,
  `Cuerpo_Cod_Cuerpo` INT NOT NULL,
  `Cuartel_Cod_Cuartel` INT NOT NULL,
  PRIMARY KEY (`cod_Soldados`),
  INDEX `fk_Soldados_Cuerpo_idx` (`Cuerpo_Cod_Cuerpo` ASC),
  INDEX `fk_Soldados_Cuartel1_idx` (`Cuartel_Cod_Cuartel` ASC),
  CONSTRAINT `fk_Soldados_Cuerpo`
    FOREIGN KEY (`Cuerpo_Cod_Cuerpo`)
    REFERENCES `mydb`.`Cuerpo` (`Cod_Cuerpo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Soldados_Cuartel1`
    FOREIGN KEY (`Cuartel_Cod_Cuartel`)
    REFERENCES `mydb`.`Cuartel` (`Cod_Cuartel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compania` (
  `Cod_Compañia` INT NOT NULL AUTO_INCREMENT,
  `Actividad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_Compañia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicios` (
  `Cod_Servicio` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Servicio` VARCHAR(45) NULL,
  PRIMARY KEY (`Cod_Servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuartel_has_Compania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuartel_has_Compania` (
  `Cuartel_Cod_Cuartel` INT NOT NULL,
  `Compania_Cod_Compañia` INT NOT NULL,
  PRIMARY KEY (`Cuartel_Cod_Cuartel`, `Compania_Cod_Compañia`),
  INDEX `fk_Cuartel_has_Compania_Compania1_idx` (`Compania_Cod_Compañia` ASC),
  INDEX `fk_Cuartel_has_Compania_Cuartel1_idx` (`Cuartel_Cod_Cuartel` ASC),
  CONSTRAINT `fk_Cuartel_has_Compania_Cuartel1`
    FOREIGN KEY (`Cuartel_Cod_Cuartel`)
    REFERENCES `mydb`.`Cuartel` (`Cod_Cuartel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuartel_has_Compania_Compania1`
    FOREIGN KEY (`Compania_Cod_Compañia`)
    REFERENCES `mydb`.`Compania` (`Cod_Compañia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Soldados_has_Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Soldados_has_Servicios` (
  `Soldados_cod_Soldados` INT NOT NULL,
  `Servicios_Cod_Servicio` INT NOT NULL,
  PRIMARY KEY (`Soldados_cod_Soldados`, `Servicios_Cod_Servicio`),
  INDEX `fk_Soldados_has_Servicios_Servicios1_idx` (`Servicios_Cod_Servicio` ASC),
  INDEX `fk_Soldados_has_Servicios_Soldados1_idx` (`Soldados_cod_Soldados` ASC),
  CONSTRAINT `fk_Soldados_has_Servicios_Soldados1`
    FOREIGN KEY (`Soldados_cod_Soldados`)
    REFERENCES `mydb`.`Soldados` (`cod_Soldados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Soldados_has_Servicios_Servicios1`
    FOREIGN KEY (`Servicios_Cod_Servicio`)
    REFERENCES `mydb`.`Servicios` (`Cod_Servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
